# **Pokémon Data Cleaning**

This notebook merges and cleans two Pokémon datasets ('poke_data.csv' and 'poke_links.csv') to prepare a final dataset for analysis and dashboard creation.

The following steps are performed:

- Load both raw CSV files as DataFrames
- Standardize Dex numbers to enable merging
- Merge datasets on Dex and Name
- Clean and normilize column names
- Handle missing values
- Fis data types
- Export cleaned DataFrame as 'pokemon_clean.csv'

## **1. Import libraries and load raw CSV files**

In [2]:
import os
import pandas as pd

In [34]:
#Loading the CSV files as new DataFrames
file_path_links = os.path.join('..', 'Data', 'poke_links.csv') #The '..' (2 dots) goes one folder up
df_links = pd.read_csv(file_path_links)

file_path_data = os.path.join('..', 'Data', 'poke_data.csv') #The '..' (2 dots) goes one folder up
df_data = pd.read_csv(file_path_data)
df_data[:5]

,Dex,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80

## **2. Standardize Dex numbers to 4-digit strings**

In [9]:
# Standardize Dex numbers to 4-digit strings with .str.zfill(4)
df_data['Dex'] = df_data['Dex'].astype(str).str.zfill(4)
df_links['Dex'] = df_links['Dex'].astype(str).str.zfill(4)
df_data[:15]

,Dex,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,0001,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
1,0002,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
2,0003,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,0004,Charmander,Fire,NaN,309,39,52,43,60,50,65
4,0005,Charmeleon,Fire,NaN,405,58,64,58,80,65,80
5,0006,Charizard,Fire,Flying,534,78,84,78,109,85,100
6,0007,Squirtle,Water,NaN,314,44,48,65,50,64,43
7,0008,Wartortle,Water,NaN,405,59,63,80,65,80,58
8,0009,Blastoise,Water,NaN,530,79,83,100,85,105,78
9,0010,Caterpie,Bug,NaN,195,45,30,35,20,20,45
10,0011,Metapod,Bug,NaN,205,50,20,55,25,25,30
11,0012,Butterfree,Bug,Flying,395,60,45,50,90,80,70
12,0013,Weedle,Bug,Poison,195,40,35,30,20,20,50
13,0014,Kakuna,Bug,Poison,205,45,25,50,25,25,35
14,0015,Beedrill,Bug,Poison,395,65,90,40,45,80,75

## **3. Preview datasets and basic structure check**

In [15]:
df_links.info()
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dex         1025 non-null   object
 1   Name        1025 non-null   object
 2   poke_links  1025 non-null   object
 3   Generation  1025 non-null   float64
 4   Image URL   1025 non-null   object
dtypes: float64(1), object(4)
memory usage: 40.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Dex      1025 non-null   object
 1   Name     1025 non-null   object
 2   Type 1   1025 non-null   object
 3   Type 2   526 non-null    object
 4   Total    1025 non-null   int64
 5   HP       1025 non-null   int64
 6   Attack   1025 non-null   int64
 7   Defense  1025 non-null   int64
 8   Sp. Atk  1025 non-null   int64
 9   Sp. Def  1025 non-null   int64
 10  Speed    1025 non-null   int64
dtypes: int64(7), object(4)
memory usage: 88.2+ KB

In [17]:
df_data.describe()

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,427.686829,70.184390,77.521951,72.507317,70.080976,70.205854,67.186341
std,112.770735,26.631054,29.782541,29.286972,29.658378,26.639329,28.717227
min,175.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000
25%,325.000000,50.000000,55.000000,50.000000,47.000000,50.000000,45.000000
50%,450.000000,68.000000,75.000000,70.000000,65.000000,67.000000,65.000000
75%,508.000000,85.000000,100.000000,90.000000,90.000000,86.000000,88.000000
max,720.000000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000

In [18]:
df_data.columns

Index(['Dex', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed'],
      dtype='object')

## **4. Check for missing values and duplicates**

In [19]:
df_data.isnull().sum()

Dex          0
Name         0
Type 1       0
Type 2     499
Total        0
HP           0
Attack       0
Defense      0
Sp. Atk      0
Sp. Def      0
Speed        0
dtype: int64

In [20]:
df_data.duplicated().sum()

0

## **5. Merge datasets on Dex and Name**

In [22]:
merged_df = pd.merge(df_data, df_links, on=['Dex', 'Name'], how='inner')
merged_df[:5]

,Dex,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,poke_links,Generation,Image URL
0,0001,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,https://pokemondb.net/pokedex/bulbasaur,1.0,https://img.pokemondb.net/artwork/large/bulbas...
1,0002,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,https://pokemondb.net/pokedex/ivysaur,1.0,https://img.pokemondb.net/artwork/large/ivysau...
2,0003,Venusaur,Grass,Poison,525,80,82,83,100,100,80,https://pokemondb.net/pokedex/venusaur,1.0,https://img.pokemondb.net/artwork/large/venusa...
3,0004,Charmander,Fire,NaN,309,39,52,43,60,50,65,https://pokemondb.net/pokedex/charmander,1.0,https://img.pokemondb.net/artwork/large/charma...
4,0005,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,https://pokemondb.net/pokedex/charmeleon,1.0,https://img.pokemondb.net/artwork/large/charme...

## **6. Clean column names for consistency**

In [25]:
merged_df.columns = (
    merged_df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
    .str.replace('.', '')
)
merged_df[:5]

,dex,name,type_1,type_2,total,hp,attack,defense,sp_atk,sp_def,speed,poke_links,generation,image_url
0,0001,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,https://pokemondb.net/pokedex/bulbasaur,1.0,https://img.pokemondb.net/artwork/large/bulbas...
1,0002,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,https://pokemondb.net/pokedex/ivysaur,1.0,https://img.pokemondb.net/artwork/large/ivysau...
2,0003,Venusaur,Grass,Poison,525,80,82,83,100,100,80,https://pokemondb.net/pokedex/venusaur,1.0,https://img.pokemondb.net/artwork/large/venusa...
3,0004,Charmander,Fire,NaN,309,39,52,43,60,50,65,https://pokemondb.net/pokedex/charmander,1.0,https://img.pokemondb.net/artwork/large/charma...
4,0005,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,https://pokemondb.net/pokedex/charmeleon,1.0,https://img.pokemondb.net/artwork/large/charme...

## **7. Fill missing values in Type 2**

In [26]:
merged_df['type_2'] = merged_df['type_2'].fillna('None')
merged_df[:5]

,dex,name,type_1,type_2,total,hp,attack,defense,sp_atk,sp_def,speed,poke_links,generation,image_url
0,0001,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,https://pokemondb.net/pokedex/bulbasaur,1.0,https://img.pokemondb.net/artwork/large/bulbas...
1,0002,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,https://pokemondb.net/pokedex/ivysaur,1.0,https://img.pokemondb.net/artwork/large/ivysau...
2,0003,Venusaur,Grass,Poison,525,80,82,83,100,100,80,https://pokemondb.net/pokedex/venusaur,1.0,https://img.pokemondb.net/artwork/large/venusa...
3,0004,Charmander,Fire,None,309,39,52,43,60,50,65,https://pokemondb.net/pokedex/charmander,1.0,https://img.pokemondb.net/artwork/large/charma...
4,0005,Charmeleon,Fire,None,405,58,64,58,80,65,80,https://pokemondb.net/pokedex/charmeleon,1.0,https://img.pokemondb.net/artwork/large/charme...

## **8. Convert generation column to integer**

In [31]:
merged_df['generation'] = merged_df['generation'].astype('int')
merged_df[200:205]

,dex,name,type_1,type_2,total,hp,attack,defense,sp_atk,sp_def,speed,poke_links,generation,image_url
200,0201,Unown,Psychic,None,336,48,72,48,72,48,48,https://pokemondb.net/pokedex/unown,2,https://img.pokemondb.net/artwork/large/unown.jpg
201,0202,Wobbuffet,Psychic,None,405,190,33,58,33,58,33,https://pokemondb.net/pokedex/wobbuffet,2,https://img.pokemondb.net/artwork/large/wobbuf...
202,0203,Girafarig,Normal,Psychic,455,70,80,65,90,65,85,https://pokemondb.net/pokedex/girafarig,2,https://img.pokemondb.net/artwork/large/girafa...
203,0204,Pineco,Bug,None,290,50,65,90,35,35,15,https://pokemondb.net/pokedex/pineco,2,https://img.pokemondb.net/artwork/large/pineco...
204,0205,Forretress,Bug,Steel,465,75,90,140,60,60,40,https://pokemondb.net/pokedex/forretress,2,https://img.pokemondb.net/artwork/large/forret...

## **9. Save cleaned dataset to CSV**

In [33]:
file_path_merged = os.path.join('..', 'Data', 'pokemon_clean.csv')
merged_df.to_csv(file_path_merged, index=False)