In [4]:
import os
import pandas as pd

In [6]:
#Loading the CSV files as new DataFrames
file_path_links = os.path.join('..', 'Data', 'poke_links.csv') #The '..' (2 dots) goes one folder up
df_links = pd.read_csv(file_path_links)

file_path_data = os.path.join('..', 'Data', 'poke_data.csv') #The '..' (2 dots) goes one folder up
df_data = pd.read_csv(file_path_data)

In [18]:
# Standardize Dex numbers to 4-digit strings with .str.zfill(4)
df_data['Dex'] = df_data['Dex'].astype(str).str.zfill(4)
df_links['Dex'] = df_links['Dex'].astype(str).str.zfill(4)
df_data[:15]

,Dex,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,0001,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
1,0002,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
2,0003,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,0004,Charmander,Fire,NaN,309,39,52,43,60,50,65
4,0005,Charmeleon,Fire,NaN,405,58,64,58,80,65,80
5,0006,Charizard,Fire,Flying,534,78,84,78,109,85,100
6,0007,Squirtle,Water,NaN,314,44,48,65,50,64,43
7,0008,Wartortle,Water,NaN,405,59,63,80,65,80,58
8,0009,Blastoise,Water,NaN,530,79,83,100,85,105,78
9,0010,Caterpie,Bug,NaN,195,45,30,35,20,20,45
10,0011,Metapod,Bug,NaN,205,50,20,55,25,25,30
11,0012,Butterfree,Bug,Flying,395,60,45,50,90,80,70
12,0013,Weedle,Bug,Poison,195,40,35,30,20,20,50
13,0014,Kakuna,Bug,Poison,205,45,25,50,25,25,35
14,0015,Beedrill,Bug,Poison,395,65,90,40,45,80,75

NameError: name 'dtype' is not defined